export const fields = [
  {
    label: "First Name",
    name: "firstName",
  },
  {
    label: "Last Name",
    name: "lastName",
  },
  {
    label: "Email",
    name: "email",
    type: "email",
  },
  {
    label: "Phone Number",
    name: "phoneNumber",
    type: "tel",
  },
  {
    label: "Middle Name",
    name: "middleName",
  },
  {
    label: "Race",
    name: "race",
  },
  {
    label: "Gender",
    name: "gender",
  },
  {
    label: "Preferred Contact Type",
    name: "preferredContactType",
  },
  {
    label: "Password",
    name: "password",
    type: "password",
  },
  {
    label: "Address Line 1",
    name: "addressLineOne",
  },
  {
    label: "Address Line 2",
    name: "addressLineTwo",
  },
  {
    label: "City",
    name: "city",
  },
  {
    label: "State",
    name: "state",
  },
  {
    label: "Country",
    name: "country",
  },
  {
    label: "Zip",
    name: "zip",
    type: "number",
  },
  {
    label: "LinkedIn",
    name: "linkedin",
  },
  {
    label: "Facebook",
    name: "facebook",
  },
  {
    label: "Twitter",
    name: "twitter",
  },
  {
    label: "Portfolio",
    name: "portfolio",
  },
  {
    label: "Website",
    name: "website",
  },
  {
    label: "Salary",
    name: "salary",
  },
  {
    label: "How did you hear about us?",
    name: "applicationReferral",
  },
  {
    label: "Current Company",
    name: "currentCompany",
  },
  {
    label: "Do you have a disability?",
    name: "disabilityStatus",
  },
  {
    label: "What's your veteran status?",
    name: "veteranStatus",
  },
  {
    label: "Are you authorized to work in the United States?",
    name: "workAuthorization",
  },
  {
    label: "Will you need immigration sponsorship for employment visa?",
    name: "immigrationSponsorship",
  },
  {
    label: "School",
    name: "school",
  },
  {
    label: "Degree",
    name: "degree",
  },
  {
    label: "Discipline",
    name: "discipline",
  },
  {
    label: "University Start Date",
    name: "universityStartDate",
    type: "number",
  },
  {
    label: "University End Date",
    name: "universityEndDate",
    type: "number",
  },
  {
    label: "Area of Interest",
    name: "areaOfInterest",
  },
  {
    label: "Security Clearance",
    name: "securityClearance"
  }
];

export type User = {
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber: number;
  middleName: string;
  isHispanic: string;
  password: string;
  contactType: string;
  addressLineOne: string;
  addressLineTwo: string;
  city: string;
  state: string;
  country: string;
  zip: number;
  linkedin: string;
  facebook: string;
  twitter: string;
  portfolio: string;
  website: string;
  salary: string;
  applicationReferral: string;
  currentCompany: string;
  workAuthorization: string;
  immigrationSponsorship: string;
  gender: string;
  race: string;
  veteranStatus: string;
  disabilityStatus: string;
  school: string;
  degree: string;
  discipline: string;
  universityStartDate: number;
  universityEndDate: number;
  areaOfInterest: string;
  securityClearance: string;
};

export const emptyUser = {
  firstName: "",
  lastName: "",
  email: "",
  phoneNumber: 0,
  middleName: "",
  isHispanic: "",
  race: "",
  gender: "",
  password: "",
  contactType: "",
  addressLineOne: "",
  addressLineTwo: "",
  city: "",
  state: "",
  country: "",
  zip: 0,
  linkedin: "",
  facebook: "",
  twitter: "",
  portfolio: "",
  website: "",
  salary: "",
  applicationReferral: "",
  currentCompany: "",
  workAuthorization: "",
  immigrationSponsorship: "",
  veteranStatus: "",
  disabilityStatus: "",
  school: "",
  degree: "",
  discipline: "",
  universityStartDate: 0,
  universityEndDate: 0,
  areaOfInterest: "",
};

export const capitalizeFirstLetter = (str: string) => {
  return str.charAt(0).toUpperCase() + str.slice(1);
};

export const STATE_ABBREVIATIONS = {
  Alabama: "AL",
  Alaska: "AK",
  Arizona: "AZ",
  Arkansas: "AR",
  California: "CA",
  Colorado: "CO",
  Connecticut: "CT",
  Delaware: "DE",
  "District of Columbia": "DC",
  Florida: "FL",
  Georgia: "GA",
  Hawaii: "HI",
  Idaho: "ID",
  Illinois: "IL",
  Indiana: "IN",
  Iowa: "IA",
  Kansas: "KS",
  Kentucky: "KY",
  Louisiana: "LA",
  Maine: "ME",
  Maryland: "MD",
  Massachusetts: "MA",
  Michigan: "MI",
  Minnesota: "MN",
  Mississippi: "MS",
  Missouri: "MO",
  Montana: "MT",
  Nebraska: "NE",
  Nevada: "NV",
  "New Hampshire": "NH",
  "New Jersey": "NJ",
  "New Mexico": "NM",
  "New York": "NY",
  "North Carolina": "NC",
  "North Dakota": "ND",
  Ohio: "OH",
  Oklahoma: "OK",
  Oregon: "OR",
  Pennsylvania: "PA",
  "Rhode Island": "RI",
  "South Carolina": "SC",
  "South Dakota": "SD",
  Tennessee: "TN",
  Texas: "TX",
  Utah: "UT",
  Vermont: "VT",
  Virginia: "VA",
  Washington: "WA",
  "West Virginia": "WV",
  Wisconsin: "WI",
  Wyoming: "WY",
};

export const COUNTRY_LIST = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Côte d'Ivoire",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Holy See",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
