COMMON_QUESTIONS = [
    {
        "question": "phone",
        "data": "phoneNumber",
    }, {
        "question": "email",
        "data": "email"
    }, {
        "question": "middle",
        "data": "middleName"
    }, {
        "question": "last",
        "data": "lastName"
    }, {
        "question": "first",
        "data": "firstName"
    }, {
        "question": "authorized",
        "data": "workAuthorization"
    }, {
        "question": "sponsorship",
        "data": "immigrantSponsorship"
    }, {
        "question": "Country",
        "data": "country"
    }, {
        "question": "job posting",
        "data": "linkedin"
    }, {
        "question": "State",
        "data": "state"
    }, {
        "question": "City",
        "data": "city"
    }, {
        "question": "Compensation",
        "data": "salary"
    }, {
        "question": "Degree",
        "data": "degree"
    }, {
        "question": "School",
        "data": "school"
    }, {
        "question": "Discipline",
        "data": "discipline"
    }, {
        "question": "Wesbite",
        "data": "wesbite"
    }, {
        "question": "LinkedIn",
        "data": "linkedin"
    }, {
        "question": "country of residence",
        "data": "country"
    }, {
        "question": "security clearance",
        "data": "securityClearance"
    }, {
        "question": "race",
        "data": "race"
    }, {
        "question": "Disability",
        "data": "disabilityStatus"
    }, {
        "question": "Veteran",
        "data": "veteranStatus"
    }, {
        "question": "Hispanic/Latino",
        "data": "isHispanic"
    }, {
        "question": "Gender",
        "data": "gender"
    }, {
        "question": "Website",
        "data": "website"
    }, {
        "question": "Github",
        "data": "github"
    }, {
        "question": "Portfolio",
        "data": "portfolio"
    }]
